name: CraftedBy Frontend Server Deploy

on:
  push:
    branches: [ "prod" ]
    paths:
      - 'version.txt'

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Set Version Environment Variable
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Build Docker image
        run: docker build . -t adrewkirts/crafted-by_frontend:latest -t adrewkirts/crafted-by_frontend:${{ env.VERSION }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push adrewkirts/crafted-by_frontend:${{ env.VERSION }}

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Set Version Environment Variable
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd dockerfiles/frontend/
            sed -i "s|adrewkirts/crafted-by_frontend:.*|adrewkirts/crafted-by_frontend:${{ env.VERSION }}|g" docker-compose.yml
            sudo docker pull adrewkirts/crafted-by_frontend:${{ env.VERSION }}
            sudo docker compose up -d